"""
Configuration models for synthetic workload generation.

All workloads configured and generated by this project are synthetic.
They are intended for local simulation and research experiments only and
must not be interpreted as real production AI inference traffic.
"""

from dataclasses import dataclass
from typing import Optional


@dataclass
class WorkloadConfig:
    """
    Configuration for generating a synthetic AI inference workload.

    Attributes:
        start_time: Start timestamp of the generated workload.
        periods: Number of time steps to generate.
        frequency: Time between consecutive workload observations.
        baseline_requests: Average baseline requests per time step.
        daily_amplitude: Strength of the daily traffic pattern.
        weekly_amplitude: Strength of the weekly traffic pattern.
        noise_std: Standard deviation of Gaussian random noise.
        random_seed: Seed used to make workload generation reproducible.
        spike_probability: Probability of a random traffic spike at each
            time step.
        spike_multiplier_min: Minimum multiplier applied during a spike.
        spike_multiplier_max: Maximum multiplier applied during a spike.
        surge_probability: Probability of starting a sudden workload surge.
        surge_duration_steps: Number of time steps a surge lasts.
        surge_multiplier: Multiplier applied to baseline traffic during a
            surge.
        peak_start_hour: Start hour of the daily peak period.
        peak_end_hour: End hour of the daily peak period.
        peak_multiplier: Traffic multiplier during peak hours.
    """

    start_time: str = "2025-01-01 00:00:00"
    periods: int = 2016
    frequency: str = "5min"

    baseline_requests: float = 100.0

    daily_amplitude: float = 40.0
    weekly_amplitude: float = 20.0
    noise_std: float = 10.0

    random_seed: Optional[int] = 42

    spike_probability: float = 0.01
    spike_multiplier_min: float = 1.5
    spike_multiplier_max: float = 3.0

    surge_probability: float = 0.002
    surge_duration_steps: int = 12
    surge_multiplier: float = 3.0

    peak_start_hour: int = 18
    peak_end_hour: int = 22
    peak_multiplier: float = 1.5