"""
Generate publication-ready figures for the
Adaptive AI Inference Optimizer experiment.

Figures are created from the exact results generated by:
    python run_strategy_comparison.py

IMPORTANT:
All figures represent results from a synthetic workload and
locally simulated AI inference infrastructure. They must not be
presented as measurements from real production infrastructure.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parent

COMPARISON_PATH = (
    PROJECT_ROOT
    / "results"
    / "tables"
    / "strategy_comparison.csv"
)

TABLES_DIR = (
    PROJECT_ROOT
    / "results"
    / "tables"
)

FIGURES_DIR = (
    PROJECT_ROOT
    / "results"
    / "figures"
)


def load_comparison_results() -> pd.DataFrame:
    """Load the exact strategy comparison results."""

    if not COMPARISON_PATH.exists():
        raise FileNotFoundError(
            "Strategy comparison results were not found.\n"
            "Run this command first:\n"
            "python run_strategy_comparison.py"
        )

    dataframe = pd.read_csv(COMPARISON_PATH)

    required_columns = [
        "strategy",
        "total_cost",
        "average_latency_ms",
        "average_estimated_p95_latency_ms",
        "total_sla_violations",
        "average_throughput",
        "total_processed_requests",
        "average_active_instances",
        "maximum_active_instances",
        "maximum_queue_length",
        "average_queue_length",
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in dataframe.columns
    ]

    if missing_columns:
        raise ValueError(
            "Missing required columns: "
            + ", ".join(missing_columns)
        )

    return dataframe


def save_figure(
    filename: str,
) -> None:
    """Save the current Matplotlib figure."""

    FIGURES_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path = FIGURES_DIR / filename

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    print(f"Saved: {output_path}")

    plt.close()


def plot_total_cost(
    dataframe: pd.DataFrame,
) -> None:
    """Plot total simulated infrastructure cost."""

    plt.figure(
        figsize=(8, 5),
    )

    plt.bar(
        dataframe["strategy"],
        dataframe["total_cost"],
    )

    plt.title(
        "Total Simulated Infrastructure Cost"
    )

    plt.xlabel(
        "Autoscaling Strategy"
    )

    plt.ylabel(
        "Total Cost"
    )

    for index, value in enumerate(
        dataframe["total_cost"]
    ):
        plt.text(
            index,
            value,
            f"{value:.2f}",
            ha="center",
            va="bottom",
        )

    save_figure(
        "total_cost_comparison.png"
    )


def plot_average_latency(
    dataframe: pd.DataFrame,
) -> None:
    """Plot average estimated latency."""

    plt.figure(
        figsize=(8, 5),
    )

    plt.bar(
        dataframe["strategy"],
        dataframe["average_latency_ms"],
    )

    plt.title(
        "Average Estimated Latency"
    )

    plt.xlabel(
        "Autoscaling Strategy"
    )

    plt.ylabel(
        "Average Latency (ms)"
    )

    for index, value in enumerate(
        dataframe["average_latency_ms"]
    ):
        plt.text(
            index,
            value,
            f"{value:.2f}",
            ha="center",
            va="bottom",
        )

    save_figure(
        "average_latency_comparison.png"
    )


def plot_p95_latency(
    dataframe: pd.DataFrame,
) -> None:
    """Plot average estimated p95 latency."""

    plt.figure(
        figsize=(8, 5),
    )

    plt.bar(
        dataframe["strategy"],
        dataframe[
            "average_estimated_p95_latency_ms"
        ],
    )

    plt.title(
        "Average Estimated P95 Latency"
    )

    plt.xlabel(
        "Autoscaling Strategy"
    )

    plt.ylabel(
        "Estimated P95 Latency (ms)"
    )

    for index, value in enumerate(
        dataframe[
            "average_estimated_p95_latency_ms"
        ]
    ):
        plt.text(
            index,
            value,
            f"{value:.2f}",
            ha="center",
            va="bottom",
        )

    save_figure(
        "p95_latency_comparison.png"
    )


def plot_sla_violations(
    dataframe: pd.DataFrame,
) -> None:
    """Plot total estimated SLA violations."""

    plt.figure(
        figsize=(8, 5),
    )

    plt.bar(
        dataframe["strategy"],
        dataframe["total_sla_violations"],
    )

    plt.title(
        "Total Estimated SLA Violations"
    )

    plt.xlabel(
        "Autoscaling Strategy"
    )

    plt.ylabel(
        "SLA Violations"
    )

    for index, value in enumerate(
        dataframe["total_sla_violations"]
    ):
        plt.text(
            index,
            value,
            f"{int(value)}",
            ha="center",
            va="bottom",
        )

    save_figure(
        "sla_violations_comparison.png"
    )


def plot_average_instances(
    dataframe: pd.DataFrame,
) -> None:
    """Plot average active instances."""

    plt.figure(
        figsize=(8, 5),
    )

    plt.bar(
        dataframe["strategy"],
        dataframe[
            "average_active_instances"
        ],
    )

    plt.title(
        "Average Active Instances"
    )

    plt.xlabel(
        "Autoscaling Strategy"
    )

    plt.ylabel(
        "Average Number of Instances"
    )

    for index, value in enumerate(
        dataframe[
            "average_active_instances"
        ]
    ):
        plt.text(
            index,
            value,
            f"{value:.2f}",
            ha="center",
            va="bottom",
        )

    save_figure(
        "average_active_instances.png"
    )


def plot_maximum_queue(
    dataframe: pd.DataFrame,
) -> None:
    """Plot maximum queue length."""

    plt.figure(
        figsize=(8, 5),
    )

    plt.bar(
        dataframe["strategy"],
        dataframe[
            "maximum_queue_length"
        ],
    )

    plt.title(
        "Maximum Simulated Queue Length"
    )

    plt.xlabel(
        "Autoscaling Strategy"
    )

    plt.ylabel(
        "Maximum Queue Length"
    )

    for index, value in enumerate(
        dataframe[
            "maximum_queue_length"
        ]
    ):
        plt.text(
            index,
            value,
            f"{int(value)}",
            ha="center",
            va="bottom",
        )

    save_figure(
        "maximum_queue_length.png"
    )


def plot_cost_vs_sla(
    dataframe: pd.DataFrame,
) -> None:
    """Create a cost versus SLA violation comparison."""

    plt.figure(
        figsize=(8, 6),
    )

    plt.scatter(
        dataframe["total_cost"],
        dataframe["total_sla_violations"],
        s=120,
    )

    for _, row in dataframe.iterrows():
        plt.annotate(
            row["strategy"],
            (
                row["total_cost"],
                row["total_sla_violations"],
            ),
            xytext=(5, 5),
            textcoords="offset points",
        )

    plt.title(
        "Cost vs Estimated SLA Violations"
    )

    plt.xlabel(
        "Total Simulated Cost"
    )

    plt.ylabel(
        "Total SLA Violations"
    )

    save_figure(
        "cost_vs_sla_violations.png"
    )


def create_summary_table(
    dataframe: pd.DataFrame,
) -> None:
    """Create a clean CSV table for use in the research paper."""

    summary_columns = [
        "strategy",
        "total_cost",
        "average_latency_ms",
        "average_estimated_p95_latency_ms",
        "total_sla_violations",
        "average_active_instances",
        "maximum_active_instances",
        "maximum_queue_length",
        "average_queue_length",
    ]

    summary = dataframe[
        summary_columns
    ].copy()

    output_path = (
        TABLES_DIR
        / "publication_results_table.csv"
    )

    summary.to_csv(
        output_path,
        index=False,
    )

    print(
        f"Saved publication table: {output_path}"
    )


def main() -> None:
    """Generate all experiment figures."""

    print("=" * 70)
    print("ADAPTIVE AI INFERENCE OPTIMIZER")
    print("PUBLICATION FIGURE GENERATION")
    print("=" * 70)

    print("\nLoading exact experiment results...")

    dataframe = load_comparison_results()

    print(
        f"Loaded results for "
        f"{len(dataframe)} strategies."
    )

    print("\nGenerating figures...")

    plot_total_cost(dataframe)

    plot_average_latency(dataframe)

    plot_p95_latency(dataframe)

    plot_sla_violations(dataframe)

    plot_average_instances(dataframe)

    plot_maximum_queue(dataframe)

    plot_cost_vs_sla(dataframe)

    print("\nCreating publication results table...")

    create_summary_table(dataframe)

    print("\n" + "=" * 70)
    print("FIGURE GENERATION COMPLETED SUCCESSFULLY")
    print("=" * 70)

    print(
        "\nIMPORTANT:"
    )

    print(
        "All figures are based on synthetic workloads "
        "and locally simulated AI inference infrastructure."
    )

    print(
        "They must be described as simulation results "
        "in any report or research paper."
    )


if __name__ == "__main__":
    main()